services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-inputfilter
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    stdin_open: true
    tty: true
