services:

  flask-inputfilter:
    build:
      context: .
      dockerfile: env_configs/cython.Dockerfile
    container_name: flask-inputfilter
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
