#!/bin/bash

echo 'Running isort'
isort /app

echo 'Running autoflake'
autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports --recursive /app

echo 'Running black'
black /app

# echo 'Running docformatter'
# docformatter --in-place /app
