name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Build Documentation
        run: |
          sphinx-build -b html docs/ _build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          preview: false
