name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install .[dev]

      - name: Build Documentation
        run: sphinx-build -b html docs/source/ _build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: _build
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          preview: false
