name: Publish to PyPI

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build-whl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install build tools
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheel with cibuildwheel
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-* cp313-* cp314-*"
          CIBW_IGNORE: "*linux_x86_64*"
          CIBW_PRERELEASE_PYTHONS: "1"
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: pkg-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./dist/*.whl

  build-whl-manylinux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install build tools
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheel (manylinux-aarch64)
        env:
          CIBW_BUILD: "cp37-manylinux_aarch64 cp38-manylinux_aarch64 cp39-manylinux_aarch64 cp310-manylinux_aarch64 cp311-manylinux_aarch64 cp312-manylinux_aarch64 cp313-manylinux_aarch64 cp314-manylinux_aarch64"
          CIBW_ARCHS: "aarch64"
          CIBW_PRERELEASE_PYTHONS: "1"
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels (manylinux-aarch64)
        uses: actions/upload-artifact@v4
        with:
          name: pkg-manylinux-aarch64
          path: ./dist/*.whl

  build-whl-musllinux-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install build tools
        run: python -m pip install cibuildwheel==2.23.3

      - name: Build wheel (musllinux-aarch64)
        env:
          CIBW_BUILD: "cp37-musllinux_aarch64 cp38-musllinux_aarch64 cp39-musllinux_aarch64 cp310-musllinux_aarch64 cp311-musllinux_aarch64 cp312-musllinux_aarch64 cp313-musllinux_aarch64 cp314-musllinux_aarch64"
          CIBW_ARCHS: "aarch64"
          CIBW_PRERELEASE_PYTHONS: "1"
        run: python -m cibuildwheel --output-dir dist

      - name: Upload wheels (musllinux-aarch64)
        uses: actions/upload-artifact@v4
        with:
          name: pkg-musllinux-aarch64
          path: ./dist/*.whl

  build-sdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: 3.11

      - name: Install build tools
        run: pip install build cython

      - name: Compile and Build package
        run: python -m build --sdist

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: pkg-sdist
          path: ./dist/*.tar.gz

  publish:
    needs: [build-whl, build-whl-manylinux-aarch64, build-whl-musllinux-aarch64, build-sdist]
    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/project/flask-inputfilter

    permissions:
      id-token: write

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v5
        with:
          path: dist
          merge-multiple: true

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
