name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install build tools
        run: pip install build twine wheel cibuildwheel

      - name: Build wheel with cibuildwheel
        env:
          CIBW_BUILD: cp37-*,cp38-*,cp39-*,cp310-*,cp311-*,cp312-*,cp313-*,cp314-*
        run: cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels-ubuntu-latest
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels-windows-latest
      - name: Download wheels
        uses: actions/download-artifact@v3
        with:
          name: wheels-macos-latest

      - name: Combine wheels
        run: mkdir dist && mv wheelhouse/* dist/

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
