name: Build and Test Library

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install build tools and test dependencies
        run: |
          pip install build pytest

      - name: Build the library
        run: |
          python -m build
        id: build

      - name: Install built library
        run: |
          pip install dist/*.whl

      - name: Verify library usage - Part I
        run: |
          echo "import flask_inputfilter" > test_script.py
          python test_script.py

      - name: Verify library usage - Part II
        run: |
          PYTHONPATH="" pytest test/
