name: Build and Test Library

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test-pure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove g++ compiler
        run: sudo apt-get remove --purge -y g++

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build tools and test dependencies
        run: pip install build pytest

      - name: Build the library
        run: python -m build
        id: build

      - name: Install built library
        run: pip install "$(ls dist/*.tar.gz | head -n 1)[optional]"

      - name: Verify library usage - Part I
        run: |
          python -c "import flask_inputfilter.InputFilter"
          python -c "from flask_inputfilter import InputFilter"

      - name: Verify library usage - Part II
        run: pytest tests/

  build-and-test-cython:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install compilers
        run: sudo apt-get install -y g++

      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build tools and test dependencies
        run: pip install build pytest

      - name: Build the library
        run: python -m build
        id: build

      - name: Install built library
        run: pip install "$(ls dist/*.tar.gz | head -n 1)[optional]"

      - name: Verify library usage - Part I
        run: |
          python -c "import flask_inputfilter.InputFilter"
          python -c "from flask_inputfilter import InputFilter"

      #- name: Verify library usage - Part II
      #  run: pytest tests/
